apiVersion: v1
kind: Service
metadata:
  name: solarsystem-service
spec:
  selector:
    app: solarsystem
  ports:
  - protocol: TCP
    port: 80        # Service port
    targetPort: 80  # Container port
  type: ClusterIP   # Use LoadBalancer for external access if needed

